apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudops-app
  template:
    metadata:
      labels:
        app: cloudops-app
    spec:
      containers:
      - name: cloudops-container
        image: chiks18/cloudops-solutions:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80