name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Minikube
        run: minikube status

      - name: Verify Kubernetes Cluster
        run: kubectl get nodes

      - name: Pull Latest Docker Image
        run: docker pull chiks18/cloudops-solutions:v1

      - name: Update Deployment Image
        run: kubectl set image deployment/cloudops-deployment cloudops-container=chiks18/cloudops-solutions:v1

      - name: Wait for Rollout
        run: kubectl rollout status deployment/cloudops-deployment

      - name: Verify Pods
        run: kubectl get pods

      - name: Verify Services
        run: kubectl get svc