name: Continuous Deployment

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Minikube
        shell: powershell
        run: |
          minikube status

      - name: Verify Kubernetes Cluster
        shell: powershell
        run: |
          kubectl get nodes

      - name: Pull Latest Docker Image
        shell: powershell
        run: |
          docker pull chiks18/cloudops-solutions:v1

      - name: Update Kubernetes Deployment
        shell: powershell
        run: |
          kubectl set image deployment/cloudops-deployment cloudops-container=chiks18/cloudops-solutions:v1

      - name: Wait for Rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/cloudops-deployment

      - name: Verify Pods
        shell: powershell
        run: |
          kubectl get pods

      - name: Verify Services
        shell: powershell
        run: |
          kubectl get svc