name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy-to-kubernetes:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Docker Image
        run: docker pull chiks18/cloudops-solutions:v1

      - name: Update Kubernetes Deployment
        run: kubectl set image deployment/cloudops-deployment cloudops-container=chiks18/cloudops-solutions:v1

      - name: Wait for Rollout
        run: kubectl rollout status deployment/cloudops-deployment